#!/bin/bash

./gradlew crashlyticsUploadDistributionProductionRelease -PbetaDistributionGroupAliases="production"
./gradlew crashlyticsUploadDistributionStagingRelease -PbetaDistributionGroupAliases="staging"
./gradlew crashlyticsUploadDistributionMockRelease -PbetaDistributionGroupAliases="mock"
./gradlew crashlyticsUploadDistributionApiaryRelease -PbetaDistributionGroupAliases="apiary"
