#!/bin/bash

python basic_upload_apks.py com.vielengames ../app/build/outputs/apk/app-production-release.apk
python basic_upload_apks.py com.vielengames.staging ../app/build/outputs/apk/app-staging-release.apk
